import React from "react";

const Home = () => {
  return (
    <div className="h-full pb-[50px  overflow-scroll bg-black flex-1  overflow-x-hidden overflow-y-visible  px-4 ">
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore suscipit
      placeat quae obcaecati! Accusamus repellat voluptatibus repudiandae et,
      laborum exercitationem mollitia cupiditate, aliquam dolorum ad eveniet
      imus voluptates hic vero praesentium amet consectetur adipisicing elit.
      Labore suscipit placeat quae obcaecati! amet consectetur adipisicing elit.
      Labore suscipit placeat quae obcaecati! Accusamus repellat voluptatibus
      repudiandae et, laborum exercitationem mollitia cupiditate, aliquam
      dolorum ad eveniet imus voluptates praesentium amet consectetur
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto distinctio labore, totam rem repellat, quibusdam quis officia enim veritatis quod asperiores magnam numquam commodi. Dolor magnam fuga veritatis sit obcaecati?
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Omnis provident deleniti nostrum quis quo error, repellendus assumenda, dolores iusto praesentium eos accusantium, inventore mollitia? Aliquam aliquid ullam necessitatibus officia accusantium delectus eligendi harum. Provident, quibusdam ipsa. Minima quisquam nemo hic doloribus atque dicta amet qui totam ipsa. Obcaecati doloribus accusantium laudantium, suscipit magni deleniti nam illum ratione voluptatem incidunt voluptatibus nihil a quas unde exercitationem iure fugiat enim aliquam animi non cum beatae! Voluptas vero repudiandae, ducimus ut iusto unde molestias dignissimos illum autem? Praesentium voluptas aut reiciendis consectetur. Pariatur quam repellendus eum doloribus, quibusdam iusto. Accusamus modi maiores iusto reiciendis rem consequatur quis sed voluptate nostrum suscipit dignissimos porro sapiente delectus quibusdam aliquid obcaecati nisi, eligendi similique aliquam, necessitatibus quasi libero nihil? Pariatur, quis. Officiis praesentium odio reiciendis veritatis accusantium dolorum eos tenetur voluptas nulla, velit alias veniam iste aut, ipsum laborum impedit voluptatibus temporibus consectetur harum neque doloremque? Recusandae nulla laudantium, sequi asperiores corporis similique neque sunt sint odit fuga obcaecati sed dignissimos, distinctio nisi voluptatem temporibus molestias voluptates sapiente quam iste exercitationem? Quis eum tempore accusamus dolores at exercitationem debitis atque temporibus, ipsum quisquam, vero distinctio minima fugiat odio autem nemo quas recusandae iure optio dignissimos in! Quas dolore rerum in? Quia eos illum accusantium laborum quas amet non provident fugiat obcaecati ad temporibus et, officia ut tempore magni, iste explicabo quis? Dicta tempore repudiandae mollitia nihil quae, ipsum dolores veritatis natus cumque nam hic ab, aliquid velit? Quasi, voluptatem velit asperiores explicabo cumque deleniti quos perferendis! Blanditiis corporis quia, repellendus deserunt eius molestiae sequi error quaerat! Illo temporibus deserunt minus ratione. Eos veniam minima cumque qui ex, eligendi soluta, maxime numquam quod, reprehenderit praesentium officiis dicta. Voluptas sequi amet praesentium possimus placeat officia, explicabo nisi mollitia non exercitationem eveniet quia tenetur dolore id iste sed. Minima!

              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi eligendi porro molestiae tempore, mollitia ratione quos odit consectetur quia hic beatae dicta quo, quibusdam labore error architecto exercitationem, rerum cupiditate inventore? Obcaecati, perspiciatis officiis. Earum omnis similique incidunt placeat laudantium deleniti. Suscipit, iusto id dolores aut voluptates, reprehenderit doloribus voluptas eveniet inventore architecto fugiat sint? Est quia magnam recusandae nesciunt tenetur minima totam quisquam consectetur repudiandae sunt ullam harum provident reprehenderit dignissimos excepturi, aliquam asperiores nisi voluptas exercitationem! Repellat ducimus eos excepturi nostrum assumenda officia impedit nesciunt adipisci hic! Numquam molestiae doloremque fugiat omnis nam natus tempore laborum, nulla corporis. Omnis reiciendis animi sequi cumque ratione, itaque veniam incidunt atque expedita dicta nam dolor nulla voluptas corporis quam, sapiente enim assumenda iure ipsam illum magnam facilis! Explicabo ullam saepe odio cum dolorem, vel, alias tenetur ab nam ipsum nemo voluptate ea labore animi quam itaque minus pariatur temporibus nihil expedita, culpa esse. Quaerat facere nesciunt odio cum enim illo, ullam reiciendis sed voluptate, deleniti veniam vel, nisi et? Delectus aut perspiciatis voluptatum, eaque iure aspernatur perferendis quo omnis error molestiae similique, laborum ipsam corporis vel magnam reprehenderit quod, nobis labore repellendus. Quia voluptatem perferendis delectus sed ex nam minima porro itaque ad nesciunt. Animi veniam ducimus alias facilis quidem quisquam odio quam voluptates dignissimos numquam eligendi corrupti debitis dolorem at, esse est illum voluptate aperiam. Laborum perferendis ab, ut eveniet maiores excepturi dolore, commodi placeat blanditiis aliquid voluptatibus dolores incidunt odit. Sit qui maxime vel quod aliquam possimus, facilis voluptate id quaerat consequatur nisi rerum a numquam, repellat tempora quasi fugit ut ab voluptates? Corrupti ducimus ipsa obcaecati ab quae quibusdam minima, consequatur alias. Odio aspernatur, veritatis autem doloremque at numquam consectetur animi facere natus dolorem, assumenda dicta! Excepturi accusantium totam aliquam ad cum dolor ullam rem eius ratione in.
    </div>
  );
};

export default Home;
